require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'mkrf/rakehelper'
require 'fileutils'
include FileUtils

setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config", "ext/**/Rakefile"]

setup_extension('trivial', 'trivial')

desc "Does a full compile"
task :default => [:trivial]

version="0.1"
name="trivial"

setup_gem(name, version) do |spec|
  spec.summary = "trivial lib"
  spec.description = spec.summary
  spec.author="Kevin Clark"
  spec.add_dependency("mkrf",">=0.1.3")
  spec.extensions = ["ext/trivial/Rakefile"]
end

task :install => [:package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end

